name: flutter_todos
description: A new Flutter application.

version: 1.0.0+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.2+1
  path: ^1.7.0
  path_provider: ^1.6.24
  http: ^0.12.2
  flutter_slidable: ^0.5.7


flutter:
  uses-material-design: true

